"""Add display_order column to tasks table

Revision ID: b74e98bdf2f0
Revises: c901bdd4d02f
Create Date: 2025-09-02 18:01:55.627163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b74e98bdf2f0'
down_revision = 'c901bdd4d02f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_order', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('display_order')

    # ### end Alembic commands ###
