name: Trigger n8n on push

on:
  push:
    # Décommente si tu veux limiter à la branche main
    # branches: [ "main" ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call n8n webhook (GET)
        run: |
          curl -fsS -X POST "https://n8n.llexahome.ovh/webhook-test/aab668c4-d788-47e5-a40a-27492eaf0782" \
            
